version: '3.8'

services:
  frontpis5to:
    build:
      context: ./pis-5to
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    container_name: frontpis5to
    environment:
      - NODE_ENV=production

  backendpist5to:
    build:
      context: ./api-pis5to
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    container_name: backendpist5to
    environment:
      - NODE_ENV=production
  